# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zedbmng.xdc

# Block Designs: bd/zedbmg_sys/zedbmg_sys.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zedbmg_sys || ORIG_REF_NAME==zedbmg_sys} -quiet] -quiet

# IP: bd/zedbmg_sys/ip/zedbmg_sys_processing_system7_0_0/zedbmg_sys_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zedbmg_sys_processing_system7_0_0 || ORIG_REF_NAME==zedbmg_sys_processing_system7_0_0} -quiet] -quiet

# IP: bd/zedbmg_sys/ip/zedbmg_sys_measdif_0_0/zedbmg_sys_measdif_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zedbmg_sys_measdif_0_0 || ORIG_REF_NAME==zedbmg_sys_measdif_0_0} -quiet] -quiet

# IP: bd/zedbmg_sys/ip/zedbmg_sys_ps7_0_axi_periph_0/zedbmg_sys_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zedbmg_sys_ps7_0_axi_periph_0 || ORIG_REF_NAME==zedbmg_sys_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zedbmg_sys/ip/zedbmg_sys_rst_ps7_0_100M_0/zedbmg_sys_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zedbmg_sys_rst_ps7_0_100M_0 || ORIG_REF_NAME==zedbmg_sys_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/zedbmg_sys/ip/zedbmg_sys_auto_pc_0/zedbmg_sys_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==zedbmg_sys_auto_pc_0 || ORIG_REF_NAME==zedbmg_sys_auto_pc_0} -quiet] -quiet

# XDC: /home/dmplab/MNGWYw26/umgn/mnghw/mnghw.gen/sources_1/bd/zedbmg_sys/zedbmg_sys_ooc.xdc
